### ISSUE TITLE
NoReverseMatch on article details page

### ISSUE THREAD

**Issue by vizo** [divio/aldryn-newsblog#360] opened 2016-02-28 15:08 UTC
Articles are listed as they should be, but when i go to article details page:

NoReverseMatch at /sl/novice/juhuhuhuhu/
Reverse for 'article-list' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []
Request Method: GET
Request URL:    http://127.0.0.1:8000/sl/novice/juhuhuhuhu/
Django Version: 1.9.2
Exception Type: NoReverseMatch
Exception Value:  
Reverse for 'article-list' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []
Exception Location: /.../env/local/lib/python2.7/site-packages/django/core/urlresolvers.py in _reverse_with_prefix, line 508
Python Executable:  /.../env/bin/python
Python Version: 2.7.10

Any idea? Thanks.

**Comment by Collederas** [comment] 2016-03-04 14:01
It looks like you did not create a page with the News&Blog Apphook

**Comment by vizo** [comment] 2016-03-09 05:41
I did all this https://github.com/aldryn/aldryn-newsblog/blob/master/docs/how_to/basic_usage.rst
I get list of articles, but when i click on it i get error above.

**Comment by vThaian** [comment] 2019-02-20 11:34
I can't reproduce that error on the newest newsblog versions. We dropped support for older. So I'm closing if you have this with the newest feel free to ping me.

**Closed by vThaian** 2019-02-20 11:34 UTC
