### ISSUE TITLE
Python 3.4 support

### ISSUE THREAD

**Issue by jonasrogert** [divio/aldryn-newsblog#134] opened 2015-03-22 21:16 UTC
Hi, Is Python 3 support something that should work (error on my side) or is it planned?

I get this error because of the use of aldryn-people and vobject already reported on aldryn-people.

https://github.com/aldryn/aldryn-people/issues/28

**Comment by mkoistinen** [comment] 2015-03-22 21:22
Yeah, the issue is that vobject was written for Python 2.4 I believe. I had a look at it to try to convert it for 3.x, but it'll be more work than I had to give at the time. So, we're looking for help there ;) Or, an up-to-date alternative for vObject support.

**Comment by mkoistinen** [comment] 2015-03-22 21:23
Yea, this is a known issue for aldryn-people as noted in its readme: https://github.com/aldryn/aldryn-people.

**Comment by jonasrogert** [comment] 2015-03-23 16:24
Alright didn't see that. I will see if i can free up some time to get a PR in order would be awesome cause newsblog fit very nicely with our latest project.

**Comment by mkoistinen** [comment] 2015-04-10 15:05
My vote on this is that we patch aldryn-people to only provide the vObject downloads when vObject is available and to then allow aldryn-people to work in Python's greater than v2.6. So, there's no change required here (yet), but I'd like to keep this open to keep pressure on aldryn-people =)

**Comment by bartmika** [comment] 2015-09-29 22:57
+1

**Comment by adambrenecki** [comment] 2015-10-21 23:22
I [submitted a patch](https://github.com/aldryn/aldryn-people/pull/104) for aldryn-people to fix this; it's been merge but doesn't appear to be in a release yet.

**Comment by rodolfomartinez** [comment] 2015-10-30 00:53
+1

**Comment by mkoistinen** [comment] 2015-10-30 01:25
I believe we'll be releasing this in the next couple of days.

**Comment by bartmika** [comment] 2015-12-08 17:41
Hey guys, I am running the blogs app with Python 3.4 so I think this issue has been fixed so you can close this ticket.

**Closed** 2019-02-14 14:19 UTC
Labels: status: issue in dependency
